'use strict';

/**
 * SAP XML export — generates read-only XML representation of a template proposal.
 * No SAP write-back in MVP. Output is for review/download only.
 */

function escapeXml(str) {
  return String(str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function stepToXml(step, indent = '    ') {
  const attrs = [
    `id="${escapeXml(step.recommendedXStep)}"`,
    `stepType="${escapeXml(step.stepType)}"`,
    `GmpRelevant="${step.gmpRelevant ? 'true' : 'false'}"`,
    `RequiresSignature="${step.requiresSignature ? 'true' : 'false'}"`,
  ].join(' ');

  const lines = [`${indent}<XStep ${attrs}>`];
  lines.push(`${indent}  <Name>${escapeXml(step.name)}</Name>`);
  lines.push(`${indent}  <Sequence>${step.sequence}</Sequence>`);
  if (step.source) {
    lines.push(`${indent}  <Source>${escapeXml(step.source)}</Source>`);
  }
  lines.push(`${indent}</XStep>`);
  return lines.join('\n');
}

/**
 * Export a template proposal as SAP-compatible XML (read-only, no write-back).
 * @param {object} template — output from composeTemplate
 * @returns {string} XML string
 */
function exportTemplateToXml(template) {
  if (!template || !Array.isArray(template.steps)) {
    throw new Error('Template with steps array is required');
  }

  const lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    `<!-- Generated by XStep Agent MVP — READ ONLY, no SAP write-back -->`,
    `<!-- validationStatus: ${escapeXml(template.validationStatus)} -->`,
    `<PISheetTemplate processArea="${escapeXml(template.processArea || '')}" packagingType="${escapeXml(template.packagingType || '')}" generatedAt="${escapeXml(template.audit?.generatedAt || new Date().toISOString())}">`,
    `  <TemplateType>${escapeXml(template.templateType || 'PI_SHEET')}</TemplateType>`,
    `  <ValidationStatus>${escapeXml(template.validationStatus)}</ValidationStatus>`,
    `  <XSteps>`,
  ];

  for (const step of template.steps) {
    lines.push(stepToXml(step));
  }

  lines.push('  </XSteps>');

  if (template.validationIssues?.length) {
    lines.push('  <ValidationIssues>');
    for (const issue of template.validationIssues) {
      lines.push(`    <Issue ruleId="${escapeXml(issue.ruleId)}" severity="${escapeXml(issue.severity)}">${escapeXml(issue.message)}</Issue>`);
    }
    lines.push('  </ValidationIssues>');
  }

  lines.push('</PISheetTemplate>');
  return lines.join('\n');
}

/**
 * Parse SAP XML import into a template-like structure (for future SAP import).
 * Currently supports the format exported by exportTemplateToXml.
 */
function importTemplateFromXml(xml) {
  const { XMLParser } = require('fast-xml-parser');
  const parser = new XMLParser({ ignoreAttributes: false, attributeNamePrefix: '@_' });
  const doc = parser.parse(xml);
  const root = doc.PISheetTemplate;
  if (!root) throw new Error('Invalid SAP XML: missing PISheetTemplate root');

  const xstepNodes = root.XSteps?.XStep || [];
  const list = Array.isArray(xstepNodes) ? xstepNodes : [xstepNodes];

  const steps = list.map((node) => ({
    sequence: Number(node.Sequence) || 0,
    stepType: node['@_stepType'] || 'PROCESS',
    name: node.Name || '',
    recommendedXStep: node['@_id'] || '',
    gmpRelevant: node['@_GmpRelevant'] === 'true',
    requiresSignature: node['@_RequiresSignature'] === 'true',
    source: node.Source || 'sap-xml-import',
  }));

  return {
    templateType: root.TemplateType || 'PI_SHEET',
    processArea: root['@_processArea'] || '',
    packagingType: root['@_packagingType'] || '',
    validationStatus: root.ValidationStatus || 'DRAFT_REQUIRES_REVIEW',
    steps,
    audit: {
      importedAt: new Date().toISOString(),
      originalGeneratedAt: root['@_generatedAt'] || null,
      source: 'sap-xml-import',
    },
  };
}

module.exports = {
  exportTemplateToXml,
  importTemplateFromXml,
  escapeXml,
};
